### PR TITLE
Fix handling of weblink repositories

### LINKED ISSUE #783: Submitter of Proxy Submission is being asked to agree to a blank deposit agreement for PMC
screen shot 2018-11-07 at 9 52 04 pm

Step to replicate
the above screenshot was obtained by the following step:
- prepare a proxy submission that will be sent to J10P AND PMC
- log in as submitter, click submit --> prompted to agree to j10p agreement, which is correct, but there's an additional step to agree to a blank popup, this is not correct.

Suspected cause:
- Ember is probably looping through the UI and displaying every repository's agreement text and asking for agreement for all of them without checking to see if there is actually any text in that field.  Such check should exist to avoid the above popup.

### PR DESCRIPTION
**Pull request by markpatton**
Changes:
- Fixes some string literal lint issues
- Use Repository.integrationType to find weblink repos
- Updates to assets image with Repository.integrationType
- Removes or comments out various debugger statements
- When creating a proxy submission
  - Do not remove weblink repositories from Submission 
  - Do not add external-submissions metadata to Submission
  - Are not required to click for weblink repositories
  - Submissions details page of new submission
    - Repositories section includes ERIC
    - No link to ERIC provided
    - No "external submission repositories" section
- When approving a proxy submission
  - Remove weblink repositories from Submission
  - Add external-submissions metadata to Submission
  - Are required to click for weblink repositories
  - Submissions details page before approval
    - Repositories section includes ERIC
    - Link to ERIC provided
    - No "external submission repositories" section
  - Submissions details page after approval
    - Repositories section does not include ERIC
    - No Link to ERIC provided
    - External submission repositories section includes ERIC
When submitting on your own behalf to grant that includes ERIC
  - Submissions details page after approval
    - Repositories section does not include ERIC
    - No Link to ERIC provided
    - External submission repositories section includes ERIC

In order to test:
1. Login as nih-user
1. Do proxy submission on behalf of Katrina Debnam
    - Associate with ERIC grant
1. Verify that:
    - Submission contains the ERIC repository
    - Submission does not have external-submissions metadata
    - No click on ERIC link was required
    - The submissions detail page is as above
1. Login as ed-user
1. Verify the submissions detail page is as above
1. Approve the submission
1. Verify that
    - Submission does not contain the ERIC repository
    - Submission does contain a external-submissions attribute containing information about the ERIC repository
    - Click on ERIC link was required
    - The submissions detail page after submission is as above

Closes #783 #775

### CODE REVIEW

**Comment by htpvu** [comment]
i'm looking at a proxy submission, which has not been submitted, as its preparer. and the `External Submission Repositories` section is shown. (see screenshot). I check the submission object in the request payload and in the fedora ui, i dont see the external repo field in the metadata blob. the repositories list attached to the submission object still contains 2 repo (J10P and ERIC). i suspect there is some special code in the submisison details that is picking up ERIC repo object and displaying it differently? 
screen shot 2018-11-08 at 4 17 51 pm

**Comment by markpatton** [comment]
@htpvu

That is the intended behavior as described above. That field is added upon submission, not approval.

**Comment by htpvu** [comment]
@markpatton i thought we agreed that "submit" means the final step of submission being complete, which happens when the self submitter click "submit" or the approver, click "submit". 

So at the point in the screenshot, the submission is not submitted yet

File: app/controllers/submissions/new.js [hunk 1]
```diff
@@ -93,17 +93,13 @@ export default Controller.extend({
...
-            repo.get('url') !== 'https://dec.usaid.gov/'
-          ))
-      );
+
+      if (!this.get('hasProxy')) {
+        sub.set(
+          'repositories',
+          sub.get('repositories').filter(repo => (repo.get('integrationType') !== 'web-link'))
+        );
+      }
```
Comment (htpvu) [inline app/controllers/submissions/new.js]: I think this block of filtering out weblink repo should happen in the block of line 47. because what we want is for web-link repo to be remove JUST before a submission is submitted for the last time.

Comment (markpatton) [reply app/controllers/submissions/new.js]: @htpvu 

The is what already happens. The code you quote above does exactly that.

Comment (markpatton) [reply app/controllers/submissions/new.js]: I suppose hasProxy could be buggy? But that probably means there are other issues. I think I tested by doing just a straight submission, but should try again.

**Comment by htpvu** [comment]
#783 did not get resolved as part of this PR.
